version: "3"

networks:
  socket_proxy:
    name: socket_proxy
    internal: true

services:
  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: dockerproxy
    networks:
      - socket_proxy
    ports: 
      - 2375:2375/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - LOG_LEVEL=info # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      ## Use 0 to revoke access / 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=${DS_POST}         # Watchtower
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=${DS_CONTAINERS} # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=${DS_IMAGES}     # Portainer
      - INFO=${DS_INFO}         # Portainer
      - NETWORKS=${DS_NETWORKS} # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=${DS_SERVICES} # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=${DS_TASKS}       # Portainer
      - VOLUMES=${DS_VOLUMES}   # Portainer