version: "3"
services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    ports:
      - "${WEB_HTTP_PORT}:5380/tcp" #DNS web console (HTTP)
      - "${WEB_HTTPS_PORT}:53443/tcp" #DNS web console (HTTPS)
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
      #- "853:853/udp" #DNS-over-QUIC service
      #- "853:853/tcp" #DNS-over-TLS service
      #- "443:443/udp" #DNS-over-HTTPS service (HTTP/3)
      #- "443:443/tcp" #DNS-over-HTTPS service (HTTP/1.1, HTTP/2)
      #- "80:80/tcp" #DNS-over-HTTP service (use with reverse proxy or certbot certificate renewal)
      #- "8053:8053/tcp" #DNS-over-HTTP service (use with reverse proxy)
      #- "67:67/udp" #DHCP service      
    environment:
      # https://github.com/TechnitiumSoftware/DnsServer/blob/master/DockerEnvironmentVariables.md
      - DNS_SERVER_DOMAIN=dns-server 
        #The primary domain name used by this DNS Server to identify itself.
      - DNS_SERVER_ADMIN_PASSWORD=${ADMIN_PASSWORD}
        #DNS web console admin user password.
      # - DNS_SERVER_PREFER_IPV6=false 
        #DNS Server will use IPv6 for querying whenever possible with this option enabled.
      - DNS_SERVER_WEB_SERVICE_HTTP_PORT=${WEB_HTTP_PORT} #5380 
        #The TCP port number for the DNS web console over HTTP protocol.
      - DNS_SERVER_WEB_SERVICE_HTTPS_PORT=${WEB_HTTPS_PORT} #53443 
        #The TCP port number for the DNS web console over HTTPS protocol.
      - DNS_SERVER_WEB_SERVICE_ENABLE_HTTPS=true 
        #Enables HTTPS for the DNS web console.
      - DNS_SERVER_WEB_SERVICE_USE_SELF_SIGNED_CERT=true
        #Enables self signed TLS certificate for the DNS web console.
      - DNS_SERVER_ENABLE_BLOCKING=true 
        #Sets the DNS server to block domain names using Blocked Zone and Block List Zone.
      # - DNS_SERVER_ALLOW_TXT_BLOCKING_REPORT=false 
        #Specifies if the DNS Server should respond with TXT records containing a blocked domain report for TXT type requests.
      - DNS_SERVER_BLOCK_LIST_URLS=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts 
        #A comma separated list of block list URLs.
      - DNS_SERVER_FORWARDERS=${FORWARDERS} #1.1.1.1, 8.8.8.8 
        #Comma separated list of forwarder addresses.
      - DNS_SERVER_FORWARDER_PROTOCOL=${FORWARDERS_PROTOCOL} #Tcp 
        #Forwarder protocol options: Udp, Tcp, Tls, Https, HttpsJson.
      - DNS_SERVER_LOG_USING_LOCAL_TIME=true 
        #Enable this option to use local time instead of UTC for logging.
    volumes:
      - config:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
 
volumes:
    config: