version: "3"
services:
  jellyfin:
    container_name: jellyfin
    hostname: ${JELLYFIN_HOSTNAME}
    image: linuxserver/jellyfin:latest
    ports:
      - "8880:8096"
      - "1900:1900" # DLNA auto-discovery
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_IP}
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/jellyfin:/config:rw
      - cache:/cache:rw
      - ${MOUNT_PATH_TV}:/data/tvshows:rw
      - ${MOUNT_PATH_MOVIES}:/data/movies:rw
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:8096 || exit 1"
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    ports:
      - "8884:6767"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/bazarr:/config:rw
      - ${MOUNT_PATH_TV}:/tv:rw
      - ${MOUNT_PATH_MOVIES}:/movies:rw
    depends_on:
      - radarr
      - sonarr
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:6767 || exit 1"
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    ports:
      - "8881:8989"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/sonarr:/config:rw
      - /temp/complete:/downloads:rw
      - ${MOUNT_PATH_TV}:/tv:rw
    depends_on:
      - sabnzbd
      - prowlarr
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:8989 || exit 1"
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    ports:
      - "8882:7878"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/radarr:/config:rw
      - /temp/complete/movies:/downloads:rw
      - ${MOUNT_PATH_MOVIES}:/movies:rw
    depends_on:
      - sabnzbd
      - prowlarr
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:7878 || exit 1"
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    ports:
      - "8883:8080"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/sabnzbd:/config:rw
      - /temp/nzbs:/nzbs:rw
      - /temp/incomplete:/incomplete-downloads:rw
      - /temp/complete:/downloads:rw
    depends_on:
      - prowlarr
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:8080 || exit 1"
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
  
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    ports:
      - 8885:9696
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/prowlarr:/config
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:9696 || exit 1"
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  cache:
