version: "3"
services:
  jellyfin:
    container_name: jellyfin
    hostname: ${JELLYFIN_HOSTNAME}
    image: linuxserver/jellyfin:latest
    ports:
      - "8880:8096"
      - "1900:1900" # DLNA auto-discovery
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_IP}
      - TZ=${TZ}
    volumes:
      - cache:/cache:rw
      - ${MOUNT_PATH_CONFIG}/jellyfin:/config:rw
      - ${MOUNT_PATH_TV}:/data/tvshows:rw
      - ${MOUNT_PATH_MOVIES}:/data/movies:rw

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    ports:
      - "8881:8989"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /temp/complete:/downloads:rw
      - ${MOUNT_PATH_TV}:/tv:rw
      - ${MOUNT_PATH_CONFIG}/sonarr:/config:rw
    depends_on:
      - sabnzbd
      - prowlarr

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    ports:
      - "8882:7878"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /temp/complete/movies:/downloads:rw
      - ${MOUNT_PATH_MOVIES}:/movies:rw
      - ${MOUNT_PATH_CONFIG}/radarr:/config:rw
    depends_on:
      - sabnzbd
      - prowlarr

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    ports:
      - "8883:8080"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /temp/nzbs:/nzbs:rw
      - /temp/incomplete:/incomplete-downloads:rw
      - /temp/complete:/downloads:rw
      - ${MOUNT_PATH_CONFIG}/sabnzbd:/config:rw
    depends_on:
      - nzbhydra2
      - prowlarr
  
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    ports:
      - 8885:9696
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${MOUNT_PATH_CONFIG}/prowlarr:/config
    restart: unless-stopped

  nzbhydra2:
    container_name: nzbhydra2
    image: linuxserver/nzbhydra2:latest
    ports:
      - "8884:5076"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /temp/nzbs:/downloads:rw
      - ${MOUNT_PATH_CONFIG}/nzbhydra2:/config:rw
    restart: unless-stopped

volumes:
  cache:
