services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      TZ: ${TZ}
    ports:
      - 8886:5055
    volumes:
      - /home/jellyseerr:/app/config:rw
      - cache:/app/cache:rw
    depends_on:
      jellyfin:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: "wget --tries=1 --spider --quiet http://localhost:5055 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
      
  jellyfin:
    container_name: jellyfin
    hostname: ${JELLYFIN_HOSTNAME}
    image: linuxserver/jellyfin:latest
    ports:
      - "8880:8096"
      - "1900:1900" # DLNA auto-discovery
    environment:
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_IP}
      - DOCKER_MODS=linuxserver/mods:jellyfin-amd # Adding mods for hardware transcoding
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/jellyfin:/config:rw
      - cache:/cache:rw
      - ${MOUNT_PATH_TV}:/data/tvshows:rw
      - ${MOUNT_PATH_MOVIES}:/data/movies:rw
    group_add:
      - "44"  # add video group for card device
      - "104" # add render group for render device
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
      - /dev/dri/card1:/dev/dri/card1
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:8096 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 240s # Occasionally needs updates, so give it  plenty of time

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:latest
    ports:
      - "8884:6767"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/bazarr:/config:rw
      - ${MOUNT_PATH_TV}:/tv:rw
      - ${MOUNT_PATH_MOVIES}:/movies:rw
    depends_on:
      radarr:
        condition: service_healthy
      sonarr:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:6767 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    ports:
      - "8881:8989"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/sonarr:/config:rw
      - /temp/complete:/downloads:rw
      - ${MOUNT_PATH_TV}:/tv:rw
    depends_on:
      sabnzbd:
        condition: service_healthy
      prowlarr:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:8989 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    ports:
      - "8882:7878"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/radarr:/config:rw
      - /temp/complete/movies:/downloads:rw
      - ${MOUNT_PATH_MOVIES}:/movies:rw
    depends_on:
      sabnzbd:
        condition: service_healthy
      prowlarr:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:7878 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  sabnzbd:
    container_name: sabnzbd
    image: linuxserver/sabnzbd:latest
    ports:
      - "8883:8080"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/sabnzbd:/config:rw
      - /temp/nzbs:/nzbs:rw
      - /temp/incomplete:/incomplete-downloads:rw
      - /temp/complete:/downloads:rw
    depends_on:
      prowlarr:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:8080 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
  
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:latest
    ports:
      - 8885:9696
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /home/prowlarr:/config
    restart: unless-stopped
    healthcheck:
      test: "curl --fail http://localhost:9696 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  maintainerr:
    image: ghcr.io/jorenn92/maintainerr:latest
    container_name: maintainerr
    depends_on:
      jellyfin:
        condition: service_healthy
    environment:
      - TZ=${TZ}
    user: ${PUID}:${PGID}
    volumes:
      - /home/maintainerr:/opt/data
    ports:
      - 6246:6246
    restart: unless-stopped
    healthcheck:
      test: "wget --tries=1 --spider --quiet http://0.0.0.0:6246 || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  cache:
