version: "3"
services:
  bedrockconnect:
    image: pugmatt/bedrock-connect:latest
    container_name: bedrockconnect
    ports:
      - "19132:19132/udp"
    environment:
      - BC_NODB=${NODB}
      - BC_CUSTOM_SERVERS=${CUSTOM_SERVERS} 
      - BC_FEATURED_SERVERS=${FEATURED_SERVERS}
      - BC_USER_SERVERS=${USER_SERVERS}
    volumes:
      - /var/lib/docker/volumes/minecraft/_data:/app/:ro
    restart: unless-stopped
      