version: "3"
services:
  bedrockconnect:
    image: ghcr.io/pheonix25/hankiz:latest
    container_name: bedrockconnect
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
    labels:
      # We're going to manually lifecycle this one
      - "com.centurylinklabs.watchtower.enable=false" 
      