version: "3"

networks:
  socket_proxy:
    name: socket_proxy
    external: true

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    networks:
      - default
      - socket_proxy
    environment:
      - DOCKER_HOST=${DOCKER_HOST}
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=${WATCHTOWER_CLEANUP}
      - WATCHTOWER_DEBUG=${WATCHTOWER_DEBUG}
      - WATCHTOWER_NOTIFICATION_LOG_STDOUT=${WATCHTOWER_NOTIFICATION_LOG_STDOUT}
      - WATCHTOWER_NOTIFICATION_URL=${WATCHTOWER_NOTIFICATION_URL}
      - WATCHTOWER_NOTIFICATION_TITLE_TAG=${WATCHTOWER_NOTIFICATION_TITLE_TAG}
      - WATCHTOWER_NOTIFICATIONS=${WATCHTOWER_NOTIFICATIONS}
      - WATCHTOWER_POLL_INTERVAL=${WATCHTOWER_POLL_INTERVAL}
    restart: unless-stopped