services:
  db:
    image: mariadb:lts
    hostname: db
    container_name: firefly_iii_db
    restart: unless-stopped
    env_file: 
      - stack.env
    networks:
      - firefly_iii
    volumes:
      - firefly_iii_db:/var/lib/mysql

  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: unless-stopped
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: 
      - stack.env
    networks:
      - firefly_iii
    ports:
      - 5000:8080
    depends_on:
      - db
        
  importer:
    image: fireflyiii/data-importer:latest
    hostname: importer
    container_name: firefly_iii_importer
    restart: unless-stopped
    env_file: 
      - stack.env
    networks:
      - firefly_iii
    ports:
      - '5001:8080'
    depends_on:
      - app
  
  cron:
    image: alpine
    restart: unless-stopped
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/L4gcCephKNfi927KUjEFUnXzAscMoubs;echo\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii
    depends_on:
      - app

volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge